% =========== $Update Time : 04-Nov-2016 17:28:40 $  =========
function cellInfo = BOUTP_outputs(varargin)
% BOUTP_outputs returns a cell array containing bus object information

% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
%                 when the m-file is executed.
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
    suppressObject = true;
elseif nargin > 1
    error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
  { ... 
    'BOUTP_outputs', ... 
    '', ... 
    sprintf(''), { ...
      {'VOUTP_StrAngReq_deg', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VOUTP_StrAngAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_StrTqReq_Nm', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VOUTP_StrTqAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_LFCTransGain_rat', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VOUTP_LFCTransGainAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_ADASLFCStatus_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VOUTP_ADASLKAStatus_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VOUTP_EPSModeReq_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VOUTP_ADAS1RollCnt_cnt', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VOUTP_PTTqReq_Nm', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VOUTP_PTTqReqAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_ForceIdle_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_ForceIdleAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_DecReq_mps2', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VOUTP_DecReqAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_AEBReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_AEBReqAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_BrakePrefillReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_BrakePrefillReqAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_VehHoldReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_BrakeHapticReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_ADASACCStatus_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VOUTP_VirtualGearRatio_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VOUTP_ADAS2RollCnt_cnt', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VOUTP_VehSpdLim_kph', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VOUTP_VehSpdLimAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_GearPosnReq_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VOUTP_GearPosnReqAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_ShiftPosnReq_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VOUTP_ShiftPosnReqAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_ADAS3RollCnt_cnt', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VOUTP_ForceLowBeam_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_ADASMILReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_HazardWarningReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_FCWWarningReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_ACCWarningReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_AEBWarningReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_IGSAWarningReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_FaultWarningReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_ACCSetSpeed_kph', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VOUTP_ADASFaultMode_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VOUTP_ACCSetTimeGap_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VOUTP_ACCSetTimeGapTmp_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VOUTP_LeftLaneLampMode_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VOUTP_RightLaneLampMode_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VOUTP_LFCHMIStatus_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VOUTP_LKAHMIStatus_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VOUTP_LFCWarningReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_ADASFunOnSoundReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_ADASFunOffSoundReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VOUTP_NumberOfTargets_num', 	1, 'uint8', -1, 'real', 'Sample'}; ...
    } ... 
  } ...
}'; 

if ~suppressObject
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end
end
