% =========== $Update Time : 27-Oct-2016 14:16:21 $  =========
function cellInfo = BFCW_outputs(varargin)
% BFCW_outputs returns a cell array containing bus object information

% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
%                 when the m-file is executed.
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
    suppressObject = true;
elseif nargin > 1
    error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
  { ... 
    'BFCW_outputs', ... 
    '', ... 
    sprintf(''), { ...
      {'VFCW_FCWSystemState_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VFCW_FCWStateHMI_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VFCW_FCWActing_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VFCW_FCWWarningReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VFCW_FCWBrakePreFillReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VFCW_FCWDecelReq_mps2', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VFCW_WarningLightsReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VFCW_FCWDecelReqAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VFCW_FCWBrakePreFillReqAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VFCW_FCWHapticReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VFCW_FCWHoldReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
    } ... 
  } ...
}'; 

if ~suppressObject
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end
end
