% =========== $Update Time : 26-Jun-2017 09:09:01 $  =========
function cellInfo = BPER_outputs(varargin)
% BPER_outputs returns a cell array containing bus object information

% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
%                 when the m-file is executed.
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
    suppressObject = true;
elseif nargin > 1
    error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
  { ... 
    'BPER_outputs', ... 
    '', ... 
    sprintf(''), { ...
      {'VPER_CameraStatus_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VPER_RadarStatus_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VPER_NumberOfTargets_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VPER_TargXPosVect30_m', 	30, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_TargYPosVect30_m', 	30, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_TargTypeVect30_enum', 	30, 'uint8', -1, 'real', 'Sample'}; ...
      {'VPER_TargAbsSpeedVect30_mps', 	30, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_TargWidthVect30_m', 	30, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_TargIdVect30_num', 	30, 'uint8', -1, 'real', 'Sample'}; ...
      {'VPER_TargAttitudeVect30_rad', 	30, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_TargExistProbVect30_num', 	30, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_FusionStatus_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VPER_TargAccelVect30_mps2', 	30, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_RadObjValidVect30_flg', 	30, 'boolean', -1, 'real', 'Sample'}; ...
      {'VPER_RadDynPropertyVect30_enum', 	30, 'uint8', -1, 'real', 'Sample'}; ...
      {'VPER_CamObsValidVect30_flg', 	30, 'boolean', -1, 'real', 'Sample'}; ...
      {'VPER_CamObsStatusVect30_enum', 	30, 'uint8', -1, 'real', 'Sample'}; ...
      {'VPER_LeftLaneAvail_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VPER_RightLaneAvail_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VPER_CenterLineC0_m', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_CenterLineC1_rad', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_CenterLineC2_rat', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_CenterLineC3_rat', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_LaneC0L_m', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_LaneC1L_rad', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_LaneC2L_rat', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_LaneC3L_rat', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_LaneC0R_m', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_LaneC1R_rad', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_LaneC2R_rat', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_LaneC3R_rat', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_TLCL_s', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_TLCR_s', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_C1LBias_rad', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_C1RBias_rad', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_ResidualLaneL_s', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VPER_ResidualLaneR_s', 	1, 'single', -1, 'real', 'Sample'}; ...
    } ... 
  } ...
}'; 

if ~suppressObject
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end
end
