/* Generated by S-function Builder */
#ifndef _DATAFUSION_BUS_H_
#define _DATAFUSION_BUS_H_
/* Read only - STARTS */
#include "tmwtypes.h"




#ifndef _DEFINED_TYPEDEF_FOR_VelocityList_
#define _DEFINED_TYPEDEF_FOR_VelocityList_ 
typedef struct {
  uint8_T count;
  uint32_T timestamp[30];
  real_T velocity[30];
} VelocityList;
#endif


#ifndef _DEFINED_TYPEDEF_FOR_YawRateList_
#define _DEFINED_TYPEDEF_FOR_YawRateList_ 
typedef struct {
  uint8_T count;
  uint32_T timestamp[30];
  real_T yawRate[30];
} YawRateList;
#endif


#ifndef _DEFINED_TYPEDEF_FOR_ObjectList_
#define _DEFINED_TYPEDEF_FOR_ObjectList_ 
typedef struct {
  uint8_T timestampCount;
  uint32_T timestamp[60];
  uint8_T objectCount[60];
  real_T x[2400];
  real_T y[2400];
  real_T vx[2400];
  real_T vy[2400];
  uint8_T rollingCounter[2400];
  uint8_T id[2400];
  real_T ax[2400];
  real_T existenceProbability[2400];
  uint8_T dynamicProperty[2400];
  real_T length[2400];
  real_T width[2400];
  uint8_T measurementStatus[2400];
  real_T rcsValue[2400];
  real_T obstacleProbability[2400];
} ObjectList;
#endif


#ifndef _DEFINED_TYPEDEF_FOR_ObstacleList_
#define _DEFINED_TYPEDEF_FOR_ObstacleList_ 
typedef struct {
  uint8_T timestampCount;
  uint32_T timestamp[60];
  uint8_T obstacleCount[60];
  real_T x[600];
  real_T y[600];
  real_T vx[600];
  real_T vy[600];
  uint8_T id[600];
  uint8_T obstacleType[600];
  uint8_T obstacleStatus[600];
  real_T length[600];
  real_T width[600];
  real_T angleRate[600];
  real_T ax[600];
  real_T angle[600];
  uint8_T obstacleTimestamp[600];
  boolean_T cipvFlag[600];
} ObstacleList;
#endif


#ifndef _DEFINED_TYPEDEF_FOR_TrackList_
#define _DEFINED_TYPEDEF_FOR_TrackList_ 
typedef struct {
  uint8_T count;
  uint32_T id[15];
  real_T x[15];
  real_T y[15];
  real_T g[15];
  real_T v[15];
  real_T a[15];
  real_T angle[15];
  real_T majorAxis[15];
  real_T minorAxis[15];
} TrackList;
#endif

/* Read only - ENDS */


#endif
