function cellInfo = R_Objects(varargin) 
% R_OBJECTS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'R_Objects', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'isComplete', [1 1], 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'received_frames1', [1 1], 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'received_frames2', [1 1], 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'StatusFrame', [1 8], 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ObS_on', [1 1], 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ObF1_on', [1 1], 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ObF2_on', [1 1], 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Frames1', [8 40], 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Frames2', [8 40], 'uint8', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
