function cellInfo = BDGI_outputs(varargin)
% VDINR_OUTPUTS returns a cell array containing bus object information
%
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
%                 when the m-file is executed.
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
    suppressObject = true;
elseif nargin > 1
    error('Invalid input argument(s) encountered');
end

cellInfo = { ...
    { ...
    'BDGI_outputs', ...
    '', ...
    sprintf(''), { ...
    {'VDGI_EPSStrAngCtlFalt_flg', 1, 'boolean', -1, 'real', 'Sample'}; ...
    {'VDGI_ESCDeceContFault_flg', 1, 'boolean', -1, 'real', 'Sample'}; ...
    {'VDGI_ECMControllerFault_flg', 1, 'boolean', -1, 'real', 'Sample'}; ...
    } ...
    } ...
    }';

if ~suppressObject
    % Create bus objects in the MATLAB base workspace
    Simulink.Bus.cellToObject(cellInfo)
end
