% =========== $Update Time : 04-Nov-2016 16:54:15 $  =========
function cellInfo = BDHP_outputs(varargin)
% BDHP_outputs returns a cell array containing bus object information

% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
%                 when the m-file is executed.
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
    suppressObject = true;
elseif nargin > 1
    error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
  { ... 
    'BDHP_outputs', ... 
    '', ... 
    sprintf(''), { ...
      {'VDHP_SystemFaultRPTimer_sec', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VDHP_SystemFaultHOTimer_sec', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VDHP_DisableADASFun_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDHP_DisableFCW_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDHP_DisableAEB_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDHP_DisableACC_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDHP_DisableLKA_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDHP_DisableLFC_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDHP_DisableMAPFun_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDHP_DisableDBS_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDHP_ADASMILReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDHP_ADASWarnMsgReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDHP_ADASWarnBuzzerReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
    } ... 
  } ...
}'; 

if ~suppressObject
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end
end
