% =========== $Update Time : 11-May-2016 09:39:16 $  =========
function cellInfo = BUDE_outputs(varargin)
% BUDE_outputs returns a cell array containing bus object information

% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
%                 when the m-file is executed.
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
    suppressObject = true;
elseif nargin > 1
    error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
  { ... 
    'BUDE_outputs', ... 
    '', ... 
    sprintf(''), { ...
      {'VUDE_TSTAMPH_ms', 	1, 'uint32', -1, 'real', 'Sample'}; ...
      {'VUDE_TSTAMPL_ms', 	1, 'uint32', -1, 'real', 'Sample'}; ...
      {'VUDE_NOFTRACKS_num', 	1, 'uint16', -1, 'real', 'Sample'}; ...
      {'VUDE_OVERLOAD_flg', 	1, 'uint16', -1, 'real', 'Sample'}; ...
      {'VUDE_TRACKSID_enum', 	30, 'uint32', -1, 'real', 'Sample'}; ...
      {'VUDE_TRACKSX_m', 	30, 'single', -1, 'real', 'Sample'}; ...
      {'VUDE_TRACKSY_m', 	30, 'single', -1, 'real', 'Sample'}; ...
      {'VUDE_TRACKSATT_rad', 	30, 'single', -1, 'real', 'Sample'}; ...
      {'VUDE_TRACKSVEL_mps', 	30, 'single', -1, 'real', 'Sample'}; ...
      {'VUDE_TRACKSCOVX_m2', 	30, 'single', -1, 'real', 'Sample'}; ...
      {'VUDE_TRACKSCOVY_m2', 	30, 'single', -1, 'real', 'Sample'}; ...
      {'VUDE_TRACKSEXSPROB_num', 	30, 'single', -1, 'real', 'Sample'}; ...
      {'VUDE_TRACKSWIDTH_m', 	30, 'single', -1, 'real', 'Sample'}; ...
      {'VUDE_TRACKSOBST_enum', 	30, 'uint8', -1, 'real', 'Sample'}; ...
      {'VUDE_TRACKSACCEL_mps2', 	30, 'single', -1, 'real', 'Sample'}; ...
      {'VUDE_TRACKSVRADAR_enum', 	30, 'uint16', -1, 'real', 'Sample'}; ...
      {'VUDE_TRACKSOBSTIDMOBILEYE_num', 	30, 'uint8', -1, 'real', 'Sample'}; ...
      {'VUDE_TRACKSOBSIDRADAR_num', 	30, 'uint8', -1, 'real', 'Sample'}; ...
      {'VUDE_TrackIsCipv_flg', 	30, 'boolean', -1, 'real', 'Sample'}; ...
      {'VUDE_CamObstacleValid_flg', 	30, 'boolean', -1, 'real', 'Sample'}; ...
      {'VUDE_RadObjectValid_flg', 	30, 'boolean', -1, 'real', 'Sample'}; ...
      {'VUDE_TRACKSRADEXISTPROB_enum', 	30, 'uint8', -1, 'real', 'Sample'}; ...
      {'VUDE_TRACKSRADOBSTPROB_num', 	30, 'uint8', -1, 'real', 'Sample'}; ...
      {'VUDE_TRACKSRADDYNSTAT_enum', 	30, 'uint8', -1, 'real', 'Sample'}; ...
      {'VUDE_TRACKSMEDYNSTAT_enum', 	30, 'uint8', -1, 'real', 'Sample'}; ...
    } ... 
  } ...
}'; 

if ~suppressObject
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end
end
