% =========== $Update Time : 22-May-2017 14:54:17 $  =========
function cellInfo = BACC_outputs(varargin)
% BACC_outputs returns a cell array containing bus object information

% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
%                 when the m-file is executed.
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
    suppressObject = true;
elseif nargin > 1
    error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
  { ... 
    'BACC_outputs', ... 
    '', ... 
    sprintf(''), { ...
      {'VACC_ACCSystemState_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VACC_ACCStateHMI_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VACC_ACCTorqueReq_Nm', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VACC_ACCDecelReq_mps2', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VACC_ACCWarningReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VACC_ACCActing_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VACC_ACCTqReqAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VACC_ACCDecelReqAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VACC_ACCRawTorqueReq_Nm', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VACC_ACCOverride_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VACC_ACCHoldReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VACC_DesiredDistance_m', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VACC_StandstillClearance_m', 	1, 'single', -1, 'real', 'Sample'}; ...
    } ... 
  } ...
}'; 

if ~suppressObject
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end
end
