% =========== $Update Time : 05-Dec-2022 18:13:33 $  =========
function cellInfo = BLIC_outputs(varargin)
% BLIC_outputs returns a cell array containing bus object information

% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
%                 when the m-file is executed.
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
    suppressObject = true;
elseif nargin > 1
    error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
  { ... 
    'BLIC_outputs', ... 
    '', ... 
    sprintf(''), { ...
      {'VLIC_LeftLaneAvail_flg', 1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VLIC_RightLaneAvail_flg', 1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VLIC_CenterLineC0_m', 1, 'single', -1, 'real', 'Sample'}; ...
      {'VLIC_CenterLineC1_rad', 1, 'single', -1, 'real', 'Sample'}; ...
      {'VLIC_CenterLineC2_rat', 1, 'single', -1, 'real', 'Sample'}; ...
      {'VLIC_CenterLineC3_rat', 1, 'single', -1, 'real', 'Sample'}; ...
      {'VLIC_LaneC0L_m', 1, 'single', -1, 'real', 'Sample'}; ...
      {'VLIC_LaneC1L_rad', 1, 'single', -1, 'real', 'Sample'}; ...
      {'VLIC_LaneC2L_rat', 1, 'single', -1, 'real', 'Sample'}; ...
      {'VLIC_LaneC3L_rat', 1, 'single', -1, 'real', 'Sample'}; ...
      {'VLIC_LaneC0R_m', 1, 'single', -1, 'real', 'Sample'}; ...
      {'VLIC_LaneC1R_rad', 1, 'single', -1, 'real', 'Sample'}; ...
      {'VLIC_LaneC2R_rat', 1, 'single', -1, 'real', 'Sample'}; ...
      {'VLIC_LaneC3R_rat', 1, 'single', -1, 'real', 'Sample'}; ...
      {'VLIC_TLCL_s', 1, 'single', -1, 'real', 'Sample'}; ...
      {'VLIC_TLCR_s', 1, 'single', -1, 'real', 'Sample'}; ...
      {'VLIC_ResidualLaneL_s', 1, 'single', -1, 'real', 'Sample'}; ...
      {'VLIC_ResidualLaneR_s', 1, 'single', -1, 'real', 'Sample'}; ...
      {'VLIC_LaneNotAvail_flg', 1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VLIC_Curvature4Act_flg', 1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VLIC_LaneWidth4Act_flg', 1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VLIC_Heading4Act_flg', 1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VLIC_Curvature4Disable_flg', 1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VLIC_TLCLTrigger_flg', 1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VLIC_TLCRTrigger_flg', 1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VLIC_LeftLaneCrossing_flg', 1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VLIC_RightLaneCrossing_flg', 1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VLIC_Curvature4DisableWarning_flg', 1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VLIC_ResidualLaneExhaust_flg', 1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VLIC_DegradedFinish_flg', 1, 'boolean', -1, 'real', 'Sample'}; ...
    } ... 
  } ...
}'; 

if ~suppressObject
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end
end
