% =========== $Update Time : 26-Jun-2017 14:42:48 $  =========
disp('Loading $Id: ifo_var.m 1597 2017-07-17 06:39:01Z bcluan $')

%% Calibration Name, Units, Min, Max, Data Type, Comment
a2l_par('KIFO_ThrottleOverrideLimit_pct', 	'pct', 	0, 	100, 	'single', 	'' );
a2l_par('KIFO_ThrottleVariationOvr_pctps', 	'pctps', 	0, 	100, 	'single', 	'' );
a2l_par('KIFO_DriverOverrideTimer_ms', 	'ms', 	0, 	10000, 	'single', 	'' );
a2l_par('KIFO_ThrottleVariationAct_pctps', 	'pctps', 	0, 	100, 	'single', 	'' );
a2l_par('KIFO_SWSActiveDriver_degps', 	'degps', 	0, 	100, 	'single', 	'' );
a2l_par('KIFO_ActiveDriverTimer_ms', 	'ms', 	0, 	10000, 	'single', 	'' );
a2l_par('KIFO_SteeringAngleParking_deg', 	'deg', 	0, 	600, 	'single', 	'' );
a2l_par('KIFO_ParkingSituationTimer_ms', 	'ms', 	0, 	10000, 	'single', 	'' );
a2l_par('KIFO_SWSAggressiveDriver_degps', 	'degps', 	0, 	100, 	'single', 	'' );
a2l_par('KIFO_ThrottleVariationAgg_pctps', 	'pctps', 	0, 	100, 	'single', 	'' );
a2l_par('KIFO_AggressiveDriverTimer_ms', 	'ms', 	0, 	10000, 	'single', 	'' );
a2l_par('KIFO_TargInPathLatOffsetFCW_m', 	'm', 	-2, 	2, 	'single', 	'' );
a2l_par('KIFO_TargInPathLatOffsetAEB_m', 	'm', 	-2, 	2, 	'single', 	'' );
a2l_par('KIFO_TargInPathLatOffsetACC_m', 	'm', 	-2, 	2, 	'single', 	'' );
a2l_par('KIFO_StraightYawRate_degps', 	'degps', 	-180, 	180, 	'single', 	'' );
a2l_par('KIFO_StraightSWARollAvg_deg', 	'deg', 	-180, 	180, 	'single', 	'' );
a2l_par('KIFO_HostVehicleWidth_m', 	'm', 	0, 	3, 	'single', 	'' );
a2l_par('KIFO_PedestrianWidth_m', 	'm', 	0, 	3, 	'single', 	'' );
a2l_par('KIFO_TTCDefault_s', 	'sec', 	0, 	30, 	'single', 	'' );
a2l_par('KIFO_ThrottlePosTimeDelay_ms', 	'ms', 	0, 	1000, 	'single', 	'' );
a2l_par('KIFO_RelSpeedNoTargets_kph', 	'kph', 	0, 	100, 	'single', 	'' );
a2l_par('KIFO_ACCRelSpeedNoTargets_kph', 	'kph', 	0, 	300, 	'single', 	'' );
a2l_par('KIFO_XPositionNoTargets_m', 	'm', 	0, 	500, 	'single', 	'' );
a2l_par('KIFO_ACCXPositionNoTargets_m', 	'm', 	0, 	500, 	'single', 	'' );
a2l_par('KIFO_SameDirecSpeed_kph', 	'kph', 	-100, 	100, 	'single', 	'' );
a2l_par('KIFO_OffsetToBumper_m', 	'm', 	0, 	10, 	'single', 	'' );
a2l_par('KIFO_DefaultTurnRad_m', 	'm', 	0, 	10000, 	'single', 	'' );
a2l_par('KIFO_FCWExistProbLimit_num', 	'num', 	0, 	1, 	'single', 	'' );
a2l_par('KIFO_AEBExistProbLimit_num', 	'num', 	0, 	1, 	'single', 	'' );
a2l_par('KIFO_ACCExistProbLimit_num', 	'num', 	0, 	1, 	'single', 	'' );
a2l_par('KIFO_TargetIdNoTargets_num', 	'num', 	0, 	30, 	'uint8', 	'' );
a2l_par('KIFO_LongAccelNoTargets_mps2', 	'mps2', 	-30, 	30, 	'single', 	'' );
a2l_par('AIFO_HMIVehSpd_mps', 	'mps', 	0, 	40, 	'single', 	'' );
a2l_par('MIFO_HMISteerSpeedLimit_degps', 	'degps', 	0, 	500, 	'single', 	'' );
a2l_par('MIFO_HMISteerAngleLimit_deg', 	'deg', 	0, 	300, 	'single', 	'' );
a2l_par('KIFO_TGapDefault_s', 	'sec', 	0, 	30, 	'single', 	'' );
a2l_par('KIFO_TGapNoTarget_s', 	'sec', 	0, 	30, 	'single', 	'' );
a2l_par('KIFO_MinOvertakeSpd_kph', 	'kph', 	0, 	200, 	'single', 	'' );
a2l_par('KIFO_DriverOvertakeTimer_ms', 	'ms', 	0, 	25000, 	'single', 	'' );
a2l_par('KIFO_MinRelOvertakeSpd_kph', 	'kph', 	0, 	100, 	'single', 	'' );
a2l_par('KIFO_BrakePressureLimit_bar', 	'bar', 	1, 	50, 	'single', 	'' );
a2l_par('KIFO_DefaultACCVehClearance_m', 	'm', 	0, 	500, 	'single', 	'' );
a2l_par('KIFO_VRUExistProbLimit_num', 	'num', 	0, 	1, 	'single', 	'' );
a2l_par('KIFO_VRUPotentiallityLimit_perc', 	'perc', 	0, 	1, 	'single', 	'' );
a2l_par('KIFO_LongPotentInc_perc', 	'num', 	0, 	50, 	'single', 	'' );
a2l_par('KIFO_ShortPotentInc_perc', 	'num', 	0, 	50, 	'single', 	'' );
a2l_par('KIFO_PotentDec_perc', 	'num', 	-50, 	0, 	'single', 	'' );
a2l_par('KIFO_PotentiallityLimit_num', 	'num', 	0, 	10000, 	'single', 	'' );
a2l_par('KIFO_ProbabTtcxThresh_s', 	'sec', 	0, 	30, 	'single', 	'' );
a2l_par('KIFO_ProbWeigInPath_perc', 	'perc', 	0, 	1, 	'single', 	'' );
a2l_par('KIFO_ProbWeigTtcx_perc', 	'perc', 	0, 	1, 	'single', 	'' );
a2l_par('KIFO_ProbWeigCrashPot_perc', 	'perc', 	0, 	1, 	'single', 	'' );
a2l_par('KIFO_TurnSignalTimer_ms', 	'ms', 	0, 	1000, 	'single', 	'' );
a2l_par('KIFO_VILOffsetToBumper_m', 	'm', 	0, 	10, 	'single', 	'' );
a2l_par('KIFO_YPositionNoTargets_m', 	'm', 	0, 	500, 	'single', 	'' );
a2l_par('KIFO_C2Max4Act_rat', 	'rat', 	0, 	250, 	'single', 	'' );
a2l_par('KIFO_Lane4ActThr_s', 	's', 	0, 	5, 	'single', 	'' );
a2l_par('KIFO_C2Max4Disable_rat', 	'rat', 	0, 	250, 	'single', 	'' );
a2l_par('KIFO_C2Max4DisableThr_s', 	's', 	0, 	5, 	'single', 	'' );
a2l_par('KIFO_C1Max4Act_rad', 	'rad', 	0, 	5, 	'single', 	'' );
a2l_par('KIFO_LaneWidthUpThr_m', 	'm', 	-1000000, 	1000000, 	'single', 	'' );
a2l_par('KIFO_LaneWidthLowThr_m', 	'm', 	-1000000, 	1000000, 	'single', 	'' );
a2l_par('AIFO_TLCThrVehSpd_X_kph', 	'kph', 	-1000000, 	1000000, 	'single', 	'' );
a2l_par('AIFO_TLCThrHeading_Y_deg', 	'deg', 	-1000000, 	1000000, 	'single', 	'' );
a2l_par('MIFO_TLCThr4LKA_s', 	's', 	-1000000, 	1000000, 	'single', 	'' );
a2l_par('KIFO_TLCTriggerThrHysis_s', 	'm', 	-1000000, 	1000000, 	'single', 	'' );
a2l_par('KIFO_LFCVehSpdMaxLimition_kph', 	'kph', 	0, 	160, 	'single', 	'' );
a2l_par('KIFO_LFCVehSpdMimLimition_kph', 	'kph', 	0, 	160, 	'single', 	'' );
a2l_par('KIFO_DriverStrSoftThres_Nm', 	'Nm', 	-1000, 	1000, 	'single', 	'' );
a2l_par('KIFO_DriverStrSoftSetTime_s', 	's', 	-1000, 	1000, 	'single', 	'' );
a2l_par('KIFO_DriverStrSoftResetTime_s', 	's', 	-1000, 	1000, 	'single', 	'' );
a2l_par('KIFO_DriverStrSoftConfirmTime_s', 	's', 	-1000, 	1000, 	'single', 	'' );
a2l_par('KIFO_DriverStrStrongThres_Nm', 	'Nm', 	-1000, 	1000, 	'single', 	'' );
a2l_par('KIFO_DriverStrStrongSetTime_s', 	's', 	-1000, 	1000, 	'single', 	'' );
a2l_par('KIFO_DriverStrStrongResetTime_s', 	's', 	-1000, 	1000, 	'single', 	'' );
a2l_par('KIFO_DriverStrStrongConfirmTime_s', 	's', 	-1000, 	1000, 	'single', 	'' );
a2l_par('KIFO_DriverStrFightThres_Nm', 	'Nm', 	-1000, 	1000, 	'single', 	'' );
a2l_par('KIFO_DriverStrFightSetTime_s', 	's', 	-1000, 	1000, 	'single', 	'' );
a2l_par('KIFO_DriverStrFightResetTime_s', 	's', 	-1000, 	1000, 	'single', 	'' );
a2l_par('KIFO_DriverStrFightConfirmTime_s', 	's', 	-1000, 	1000, 	'single', 	'' );
a2l_par('KIFO_DriverStrStrongThresHys_Nm', 	'Nm', 	-1000, 	1000, 	'single', 	'' );
a2l_par('KIFO_DriverStrFightThresHys_Nm', 	'Nm', 	-1000, 	1000, 	'single', 	'' );
a2l_par('KIFO_TurnSignalSwOFFTime_s', 	's', 	-1000, 	1000, 	'single', 	'' );
a2l_par('KIFO_LKAMaxActSpeed_kph', 	'kph', 	0, 	160, 	'single', 	'' );
a2l_par('KIFO_LKAMinActSpeed_kph', 	'kph', 	0, 	160, 	'single', 	'' );
a2l_par('KIFO_LKAMaxDeactSpeed_kph', 	'kph', 	0, 	160, 	'single', 	'' );
a2l_par('KIFO_LKAMinDeactSpeed_kph', 	'kph', 	0, 	160, 	'single', 	'' );

%% Monitored Signals
% Module Signals %
a2l_mon('VIFO_FCWMCVehXPosition_m', 	'm', 	0, 	500, 	'single', 	'',	1 );
a2l_mon('VIFO_AEBMCVehXPosition_m', 	'm', 	0, 	500, 	'single', 	'',	1 );
a2l_mon('VIFO_ACCMCVehXPosition_m', 	'm', 	0, 	500, 	'single', 	'',	1 );
a2l_mon('VIFO_FCWVehInPathVect30_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	30 );
a2l_mon('VIFO_AEBVehInPathVect30_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	30 );
a2l_mon('VIFO_ACCVehInPathVect30_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	30 );
a2l_mon('VIFO_TargAbsDistanceVect30_m', 	'm', 	0, 	500, 	'single', 	'',	30 );
a2l_mon('VIFO_AEBTargetIsVehVect30_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	30 );
a2l_mon('VIFO_ACCTargetIsVehVect30_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	30 );
a2l_mon('VIFO_AEBTargetIsPedVect30_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	30 );
a2l_mon('VIFO_AEBTargetSameDirVect30_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	30 );
a2l_mon('VIFO_ACCTargetSameDirVect30_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	30 );
a2l_mon('VIFO_TargVehRelSpdXVect30_mps', 	'mps', 	-100, 	100, 	'single', 	'',	30 );
a2l_mon('VIFO_FCWMCTTargId_num', 	'num', 	0, 	30, 	'uint8', 	'',	1 );
a2l_mon('VIFO_AEBMCTTargId_num', 	'num', 	0, 	30, 	'uint8', 	'',	1 );
a2l_mon('VIFO_ACCMCTTargId_num', 	'num', 	0, 	30, 	'uint8', 	'',	1 );
a2l_mon('VIFO_SteeringTransOvr_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_ThrotPosTransOvr_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_ThrotVarTransOvr_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_BrakePedalTransOvr_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_SWSAggressiveTrans_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_ThrotAggressiveTrans_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_SWSActiveTrans_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_ThrotActiveTrans_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_GearParkingTrans_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_SteerParkingTrans_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_ParkingBrakeOnTrans_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_PositionToPathVect30_m', 	'm', 	0, 	50, 	'single', 	'',	30 );
a2l_mon('VIFO_FCWPathBoundVect30_m', 	'm', 	0, 	50, 	'single', 	'',	30 );
a2l_mon('VIFO_AEBPathBoundVect30_m', 	'm', 	0, 	50, 	'single', 	'',	30 );
a2l_mon('VIFO_ACCPathBoundVect30_m', 	'm', 	0, 	50, 	'single', 	'',	30 );
a2l_mon('VIFO_TargAbsSpeedXVect30_mps', 	'mps', 	-100, 	100, 	'single', 	'',	30 );
a2l_mon('VIFO_TargAbsSpeedYVect30_mps', 	'mps', 	-100, 	100, 	'single', 	'',	30 );
a2l_mon('VIFO_TargAccelXVect30_mps2', 	'mps2', 	-30, 	30, 	'single', 	'',	30 );
a2l_mon('VIFO_VRUMCTTargId_num', 	'num', 	0, 	30, 	'uint8', 	'',	1 );
a2l_mon('VIFO_PotentiallityVect30_num', 	'num', 	0, 	10000, 	'single', 	'',	30 );
a2l_mon('VIFO_VRUMCPedXPosition_m', 	'm', 	0, 	500, 	'single', 	'',	1 );
a2l_mon('VIFO_VRUMCLongAcc_mps2', 	'mps2', 	0, 	20, 	'single', 	'',	1 );

% Output Signals %
a2l_mon('VIFO_DriverSafetyStatusOk_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_VehicleStatusOk_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_DriverOverrideReq_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_AggressiveDriverDetec_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_ActiveDriverDetec_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_ParkingSituation_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_BrakePedalPressed_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_ACCTurnOnReq_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_ACCTurnOffReq_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_ACCCancelReq_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_DriverOvertakeReq_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_FCWVehClearance_m', 	'm', 	0, 	500, 	'single', 	'',	1 );
a2l_mon('VIFO_FCWTargetVehicleTtcX_ms', 	'ms', 	-5000, 	5000, 	'single', 	'',	1 );
a2l_mon('VIFO_FCWTargetVehRelSpeedX_mps', 	'mps', 	-100, 	100, 	'single', 	'',	1 );
a2l_mon('VIFO_AEBVehClearance_m', 	'm', 	0, 	500, 	'single', 	'',	1 );
a2l_mon('VIFO_AEBTargetVehicleTtcX_ms', 	'ms', 	-5000, 	5000, 	'single', 	'',	1 );
a2l_mon('VIFO_ACCTargetVehicleTtcX_ms', 	'ms', 	-5000, 	5000, 	'single', 	'',	1 );
a2l_mon('VIFO_AEBTargetVehRelSpeedX_mps', 	'mps', 	-100, 	100, 	'single', 	'',	1 );
a2l_mon('VIFO_FCWTargetVehAssigned_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_AEBTargetVehAssigned_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_ACCTargetVehAssigned_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_FCWMCVehId_num', 	'num', 	0, 	30, 	'uint8', 	'',	1 );
a2l_mon('VIFO_AEBMCVehId_num', 	'num', 	0, 	30, 	'uint8', 	'',	1 );
a2l_mon('VIFO_ACCMCVehId_num', 	'num', 	0, 	30, 	'uint8', 	'',	1 );
a2l_mon('VIFO_ACCTargetVehRelSpeedX_mps', 	'mps', 	-100, 	100, 	'single', 	'',	1 );
a2l_mon('VIFO_ACCTGap_s', 	's', 	-10, 	10, 	'single', 	'',	1 );
a2l_mon('VIFO_ACCVehClearance_m', 	'm', 	0, 	500, 	'single', 	'',	1 );
a2l_mon('VIFO_AEBMCLongAcc_mps2', 	'mps2', 	0, 	20, 	'single', 	'',	1 );
a2l_mon('VIFO_FCWMCLongAcc_mps2', 	'mps2', 	0, 	20, 	'single', 	'',	1 );
a2l_mon('VIFO_ACCMCLongAcc_mps2', 	'mps2', 	0, 	20, 	'single', 	'',	1 );
a2l_mon('VIFO_ACCSetSpdDec_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_ACCResSpdInc_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_ACCDist_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_AEBTGap_s', 	's', 	-10, 	10, 	'single', 	'',	1 );
a2l_mon('VIFO_FCWTGap_s', 	's', 	-10, 	10, 	'single', 	'',	1 );
a2l_mon('VIFO_VRUPedClearance_m', 	'm', 	0, 	500, 	'single', 	'',	1 );
a2l_mon('VIFO_VRUTargetPedTtcX_ms', 	'ms', 	-5000, 	5000, 	'single', 	'',	1 );
a2l_mon('VIFO_VRUTargetPedAssigned_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_VRUMCPedId_num', 	'num', 	0, 	30, 	'uint8', 	'',	1 );
a2l_mon('VIFO_VRUTargetPedRelSpeedX_mps', 	'mps', 	-100, 	100, 	'single', 	'',	1 );
a2l_mon('VIFO_DriverTurnSignalOn_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_LaneNotAvail_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_Curvature4Act_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_LaneWidth4Act_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_Heading4Act_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_Curvature4Disable_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_TLCLTrigger_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_TLCRTrigger_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_LeftLaneCrossing_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_RightLaneCrossing_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_Curvature4DisableWarning_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_LFCSpdInRange_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_LKASpdInRange_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_InForwardGear_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_SelInForwardGear_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_DriverStrSoft_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_DriverStrSoftConfi_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_DriverStrStrong_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_DriverStrStrongConfi_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_DriverStrFight_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_DriverStrFightConfi_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_DriverTurningSignal_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_DriverShifting_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_DriverTurningSignalSwL_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_DriverTurningSignalSwR_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_DriverHOD_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_DriverHOD4Disabled_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_LatVehicleStatusOk_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_ResidualLaneFinish_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_DegradedFinish_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
a2l_mon('VIFO_EPSStateChgAllow_flg', 	'flg', 	0, 	1, 	'boolean', 	'',	1 );
