% =========== $Update Time : 04-Nov-2016 16:52:36 $  =========
function cellInfo = BDFR_outputs(varargin)
% BDFR_outputs returns a cell array containing bus object information

% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
%                 when the m-file is executed.
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
    suppressObject = true;
elseif nargin > 1
    error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
  { ... 
    'BDFR_outputs', ... 
    '', ... 
    sprintf(''), { ...
      {'VDFR_SysPowerDownCmd_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_StrAngReq_deg', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VDFR_StrAngAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_StrTqReq_Nm', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VDFR_StrTqAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_LFCTransGain_rat', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VDFR_LFCTransGainAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_ADASLFCStatus_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VDFR_ADASLKAStatus_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VDFR_EPSModeReq_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VDFR_PTTqReq_Nm', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VDFR_PTTqReqAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_ForceIdle_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_ForceIdleAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_DecReq_mps2', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VDFR_DecReqAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_AEBReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_AEBReqAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_BrakePrefillReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_BrakePrefillReqAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_VehHoldReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_BrakeHapticReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_ADASACCStatus_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VDFR_VirtualGearRatio_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VDFR_VehSpdLim_kph', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VDFR_VehSpdLimAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_GearPosnReq_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VDFR_GearPosnReqAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_ShiftPosnReq_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VDFR_ShiftPosnReqAppl_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_ForceLowBeam_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_ADASMILReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_HazardWarningReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_FCWWarningReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_ACCWarningReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_AEBWarningReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_IGSAWarningReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_FaultWarningReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_ACCSetSpeed_kph', 	1, 'single', -1, 'real', 'Sample'}; ...
      {'VDFR_ADASFaultMode_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VDFR_ACCSetTimeGap_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VDFR_ACCSetTimeGapTmp_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VDFR_LeftLaneLampMode_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VDFR_RightLaneLampMode_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VDFR_LFCHMIStatus_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VDFR_LKAHMIStatus_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VDFR_LFCWarningReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_ADASFunOnSoundReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_ADASFunOffSoundReq_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VDFR_NumberOfTargets_num', 	1, 'uint8', -1, 'real', 'Sample'}; ...
    } ... 
  } ...
}'; 

if ~suppressObject
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end
end
