% =========== $Update Time : 11-Jan-2017 11:23:35 $  =========
function cellInfo = BLKA_outputs(varargin)
% BLKA_outputs returns a cell array containing bus object information

% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
%                 when the m-file is executed.
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
    suppressObject = true;
elseif nargin > 1
    error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
  { ... 
    'BLKA_outputs', ... 
    '', ... 
    sprintf(''), { ...
      {'VLKA_LKAState_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VLKA_LKAActing_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VLKA_LKAStrTqReq_Nm', 	1, 'single', -1, 'real', 'Sample'}; ...
    } ... 
  } ...
}'; 

if ~suppressObject
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end
end
