% =========== $Update Time : 01-Jun-2017 09:43:45 $  =========
function cellInfo = BLFC_outputs(varargin)
% BLFC_outputs returns a cell array containing bus object information

% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject
%                 when the m-file is executed.
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode

suppressObject = false;
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false
    suppressObject = true;
elseif nargin > 1
    error('Invalid input argument(s) encountered');
end

cellInfo = { ... 
  { ... 
    'BLFC_outputs', ... 
    '', ... 
    sprintf(''), { ...
      {'VLFC_LFCState_enum', 	1, 'uint8', -1, 'real', 'Sample'}; ...
      {'VLFC_LFCActing_flg', 	1, 'boolean', -1, 'real', 'Sample'}; ...
      {'VLFC_LFCStrAngReq_deg', 	1, 'single', -1, 'real', 'Sample'}; ...
    } ... 
  } ...
}'; 

if ~suppressObject
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end
end
